# Generated by Django 3.1.7 on 2021-03-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('slug', models.SlugField(null=True, verbose_name='هشتگ')),
                ('thumb', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
